db.restaurants.find().pretty();
db.restaurants.find({}, { restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({}, { _id: false, restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({}, { _id: false, restaurant_id: true, name: true, borough: true, 'address.zipcode': true }).pretty();
db.restaurants.find({ borough: 'Bronx' }).pretty();
db.restaurants.find({ borough: 'Bronx' }).limit(5).pretty();
db.restaurants.find({ borough: 'Bronx' }).skip(5).limit(5).pretty();
db.restaurants.find({ 'grades.score': { $gt: 90 } }).pretty();
db.restaurants.find({ 'grades.score': { $gt: 80, $lt: 100 } }).pretty();
db.restaurants.find({ 'address.coord.0': { $lt: - 95.754168 } }).pretty();
db.restaurants.find({ $and: [{ cuisine: { $ne: 'American ' }, 'grades.score': { $gt: 70 }, 'address.coord.0': { $lt: - 65.754168 } }] }).pretty();
db.restaurants.find({ cuisine: { $ne: 'American ' }, 'grades.score': { $gt: 70 }, 'address.coord.0': { $lt: - 65.754168 } }).pretty();
db.restaurants.find({ cuisine: { $ne: 'American ' }, 'grades.grade': 'A', borough: { $ne: 'Brooklyn' }}).sort({ cuisine: -1 }).pretty();
db.restaurants.find({ name: /^Wil/ }, { restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({ name: /ces$/ }, { restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({ name: /Reg/ }, { restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({ borough: 'Bronx', $or: [{ cuisine: /American/ }, { cuisine: /Chinese/ }] }).pretty();
db.restaurants.find({ borough: {$in: ['Staten Island','Queens','Bronx','Brooklyn']} }, { restaurant_id: true, name: true, borough: true, cuisine: true}).pretty();
db.restaurants.find({ borough: {$nin: ['Staten Island','Queens','Bronx','Brooklyn']} }, { restaurant_id: true, name: true, borough: true, cuisine: true}).pretty();
db.restaurants.find({ 'grades.score': { $lt: 10 } }, { restaurant_id: true, name: true, borough: true, cuisine: true }).pretty();
db.restaurants.find({ $or: [{ $and: [{ cuisine: 'Seafood' }, { cuisine: { $ne: 'American ' } }, { cuisine: { $ne: 'Chinese' } }] }, { name: /^Wil/ }] }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 }).pretty();
db.restaurants.find({'grades.date': ISODate("2014-08-11T00:00:00Z"), 'grades.grade': 'A' , 'grades.score' : 11}, { restaurant_id: 1, name:1, grades: 1 }).pretty();
db.restaurants.find({ 'grades.1.date': ISODate("2014-08-11T00:00:00Z"), 'grades.1.grade': 'A' , 'grades.1.score' : 9}, {restaurant_id: 1, name: 1, grades: 1}).pretty();
db.restaurants.find({ 'address.coord.1': { $gt: 42, $lte: 52 } }, { restaurant_id: 1, name:1, address: 1 }).pretty();
db.restaurants.find().sort({ name: 1 }).pretty();
db.restaurants.find().sort({ name: -1 }).pretty();
db.restaurants.find().sort({ cuisine: 1, borough: -1 }).pretty();
db.restaurants.find({ 'address.street': { $exists: false } }).pretty();
db.restaurants.find({ 'address.coord': { $type: 'double' } }).pretty();
db.restaurants.find({ 'grades.score': { $mod: [7,0] } },{ restaurant_id: 1, name: 1, grades: 1 }).pretty();
db.restaurants.find({ name: /mon/ }, { name: 1, borough: 1, 'address.coord': 1, cuisine: 1 }).pretty();
db.restaurants.find({ name: /^Mad/ }, { name: 1, borough: 1, 'address.coord': 1, cuisine: 1 }).pretty();

