-- MySQL Script generated by MySQL Workbench
-- Wed 12 May 2021 06:02:11 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CHAT
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CHAT` ;

-- -----------------------------------------------------
-- Schema CHAT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CHAT` ;
USE `CHAT` ;

-- -----------------------------------------------------
-- Table `CHAT`.`rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHAT`.`rooms` ;

CREATE TABLE IF NOT EXISTS `CHAT`.`rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CHAT`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHAT`.`users` ;

CREATE TABLE IF NOT EXISTS `CHAT`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `socket_id` VARCHAR(30) NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `room_id`),
  INDEX `fk_users_rooms1_idx` (`room_id` ASC) VISIBLE,
  UNIQUE INDEX `socket_id_UNIQUE` (`socket_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_rooms1`
    FOREIGN KEY (`room_id`)
    REFERENCES `CHAT`.`rooms` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CHAT`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CHAT`.`messages` ;

CREATE TABLE IF NOT EXISTS `CHAT`.`messages` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(500) NOT NULL,
  `room_id` INT NOT NULL,
  PRIMARY KEY (`message_id`, `room_id`),
  INDEX `fk_messages_rooms_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_rooms`
    FOREIGN KEY (`room_id`)
    REFERENCES `CHAT`.`rooms` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
