-- MySQL Script generated by MySQL Workbench
-- Tue 30 Mar 2021 01:30:22 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DICE-GAME_I
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DICE-GAME_I` ;

-- -----------------------------------------------------
-- Schema DICE-GAME_I
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DICE-GAME_I` ;
USE `DICE-GAME_I` ;

-- -----------------------------------------------------
-- Table `DICE-GAME_I`.`players`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DICE-GAME_I`.`players` ;

CREATE TABLE IF NOT EXISTS `DICE-GAME_I`.`players` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `registered_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `average` DECIMAL(3,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DICE-GAME_I`.`games`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DICE-GAME_I`.`games` ;

CREATE TABLE IF NOT EXISTS `DICE-GAME_I`.`games` (
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `dice_1_result` INT NOT NULL,
  `dice_2_result` INT NOT NULL,
  `score` ENUM('WIN', 'LOSS') NOT NULL,
  `player_id` INT NOT NULL,
  PRIMARY KEY (`game_id`),
  INDEX `fk_games_players_idx` (`player_id` ASC) VISIBLE,
  CONSTRAINT `fk_games_players`
    FOREIGN KEY (`player_id`)
    REFERENCES `DICE-GAME_I`.`players` (`player_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
