-- MySQL Script generated by MySQL Workbench
-- Wed 03 Feb 2021 12:50:11 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PIZZERIA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PIZZERIA` ;

-- -----------------------------------------------------
-- Schema PIZZERIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PIZZERIA` DEFAULT CHARACTER SET utf8mb4 ;
USE `PIZZERIA` ;

-- -----------------------------------------------------
-- Table `PIZZERIA`.`provinces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`provinces` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`provinces` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`cities` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  INDEX `fk_cities_provinces1_idx` (`province_id` ASC) VISIBLE,
  CONSTRAINT `fk_cities_provinces1`
    FOREIGN KEY (`province_id`)
    REFERENCES `PIZZERIA`.`provinces` (`province_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`customers` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surnames` VARCHAR(50) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customers_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_customers_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `PIZZERIA`.`cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`stores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`stores` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`stores` (
  `store_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`store_id`),
  INDEX `fk_stores_cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_stores_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `PIZZERIA`.`cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`orders` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `delivery_location` ENUM('home', 'store') NOT NULL DEFAULT 'home',
  `total_price` DECIMAL(6,2) NOT NULL,
  `customer_id` INT NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_orders_stores1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `PIZZERIA`.`customers` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_orders_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `PIZZERIA`.`stores` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`employees` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `surnames` VARCHAR(50) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `job_position` ENUM('delivery', 'cook') NOT NULL,
  `store_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employees_stores1_idx` (`store_id` ASC) VISIBLE,
  CONSTRAINT `fk_employees_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `PIZZERIA`.`stores` (`store_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`pizza_categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`pizza_categories` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`pizza_categories` (
  `pizza_category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`pizza_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`products` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `picture` BLOB NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `pizza_category_id` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_pizza_categories1_idx` (`pizza_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_pizza_categories1`
    FOREIGN KEY (`pizza_category_id`)
    REFERENCES `PIZZERIA`.`pizza_categories` (`pizza_category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`order_details` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`order_details` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity_ordered` INT NOT NULL,
  INDEX `fk_order_details_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_details_products1_idx` (`product_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`, `product_id`),
  CONSTRAINT `fk_order_details_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `PIZZERIA`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_details_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `PIZZERIA`.`products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIZZERIA`.`home_orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIZZERIA`.`home_orders` ;

CREATE TABLE IF NOT EXISTS `PIZZERIA`.`home_orders` (
  `order_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `delivered_date` DATETIME NOT NULL,
  INDEX `fk_home_orders_orders1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_home_orders_employees1_idx` (`employee_id` ASC) VISIBLE,
  PRIMARY KEY (`order_id`, `employee_id`),
  CONSTRAINT `fk_home_orders_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `PIZZERIA`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_home_orders_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `PIZZERIA`.`employees` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
