-- MySQL Script generated by MySQL Workbench
-- Wed 10 Feb 2021 09:56:06 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SPOTIFY
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SPOTIFY` ;

-- -----------------------------------------------------
-- Schema SPOTIFY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SPOTIFY` ;
USE `SPOTIFY` ;

-- -----------------------------------------------------
-- Table `SPOTIFY`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`users` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('free', 'premium') NOT NULL DEFAULT 'free',
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `dob` DATE NULL,
  `gender` ENUM('man', 'female') NULL,
  `country` VARCHAR(50) NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`subscriptions` (
  `subscription_id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `renovation_date` DATETIME NOT NULL,
  `payment_method` ENUM('Credit Card', 'PayPal') NOT NULL,
  PRIMARY KEY (`subscription_id`),
  CONSTRAINT `fk_subscriptions_users`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`paypals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`paypals` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`paypals` (
  `paypal_id` INT NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`paypal_id`),
  CONSTRAINT `fk_paypals_subscriptions`
    FOREIGN KEY (`paypal_id`)
    REFERENCES `SPOTIFY`.`subscriptions` (`subscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`creditcards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`creditcards` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`creditcards` (
  `creditcard_id` INT NOT NULL,
  `number` INT NOT NULL,
  `month` INT NOT NULL,
  `year` INT NOT NULL,
  `security_code` INT NOT NULL,
  PRIMARY KEY (`creditcard_id`),
  CONSTRAINT `fk_creditcards_subscriptions`
    FOREIGN KEY (`creditcard_id`)
    REFERENCES `SPOTIFY`.`subscriptions` (`subscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`payments` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`payments` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(45) NOT NULL,
  `order_number` INT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `subscription_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `payments_paymentNum_UNIQUE` (`order_number` ASC) VISIBLE,
  INDEX `fk_payments_subscription1_idx` (`subscription_id` ASC) VISIBLE,
  CONSTRAINT `fk_payments_subscriptions`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `SPOTIFY`.`subscriptions` (`subscription_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`playlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`playlists` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`playlists` (
  `playlist_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `total_songs` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
  `shared` TINYINT NOT NULL DEFAULT 0,
  `deleted_at` DATETIME NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`playlist_id`),
  INDEX `fk_playlists_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`artists` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`artists` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `photo` BLOB NOT NULL,
  PRIMARY KEY (`artist_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`albums` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`albums` (
  `album_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `year` DATE NOT NULL,
  `picture` BLOB NOT NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`album_id`),
  INDEX `fk_album_artist1_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_albums_artists`
    FOREIGN KEY (`artist_id`)
    REFERENCES `SPOTIFY`.`artists` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`songs` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`songs` (
  `song_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `length` TIME NOT NULL DEFAULT '00:00:00',
  `reproductions` INT NOT NULL DEFAULT 0,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`song_id`),
  INDEX `fk_song_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_songs_albums`
    FOREIGN KEY (`album_id`)
    REFERENCES `SPOTIFY`.`albums` (`album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`playlist_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`playlist_songs` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`playlist_songs` (
  `playlist_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  `user_id` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_playlist_songs_playlists1_idx` (`playlist_id` ASC) VISIBLE,
  INDEX `fk_playlist_songs_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_playlist_songs_songs1_idx` (`song_id` ASC) VISIBLE,
  PRIMARY KEY (`playlist_id`, `song_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_songs_playlists`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `SPOTIFY`.`playlists` (`playlist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_songs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_playlist_songs_songs`
    FOREIGN KEY (`song_id`)
    REFERENCES `SPOTIFY`.`songs` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`similar_artists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`similar_artists` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`similar_artists` (
  `artist_id` INT NOT NULL,
  `similar_artist_id` INT NOT NULL,
  INDEX `fk_similar_artists_artists1_idx` (`artist_id` ASC) VISIBLE,
  INDEX `fk_similar_artists_artists1_idx1` (`similar_artist_id` ASC) VISIBLE,
  PRIMARY KEY (`artist_id`, `similar_artist_id`),
  CONSTRAINT `fk_similar_artists_artists`
    FOREIGN KEY (`artist_id`)
    REFERENCES `SPOTIFY`.`artists` (`artist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_similar_artists_artists1`
    FOREIGN KEY (`similar_artist_id`)
    REFERENCES `SPOTIFY`.`artists` (`artist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`following_artits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`following_artits` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`following_artits` (
  `user_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `artist_id`),
  INDEX `fk_user_has_artist_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_following_artits_artists1_idx` (`artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_following_artists`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_following_artits_artists`
    FOREIGN KEY (`artist_id`)
    REFERENCES `SPOTIFY`.`artists` (`artist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`favorite_albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`favorite_albums` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`favorite_albums` (
  `user_id` INT NOT NULL,
  `album_id` INT NOT NULL,
  INDEX `fk_favorite_albums_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_favorite_albums_albums1_idx` (`album_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`, `album_id`),
  CONSTRAINT `fk_favorite_albums_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorite_albums_albums`
    FOREIGN KEY (`album_id`)
    REFERENCES `SPOTIFY`.`albums` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPOTIFY`.`favorite_songs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SPOTIFY`.`favorite_songs` ;

CREATE TABLE IF NOT EXISTS `SPOTIFY`.`favorite_songs` (
  `user_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `song_id`),
  INDEX `fk_favorite_songs_songs1_idx` (`song_id` ASC) VISIBLE,
  INDEX `fk_favorite_songs_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorite_songs_songs1`
    FOREIGN KEY (`song_id`)
    REFERENCES `SPOTIFY`.`songs` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorite_songs_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPOTIFY`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
